services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: tbs_app
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        depends_on:
            - mysql
        networks:
            - tbs_net
        dns:
            - 1.1.1.1
            - 8.8.8.8

    nginx:
        image: nginx:alpine
        container_name: tbs_nginx
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - app
        networks:
            - tbs_net
        dns:
            - 1.1.1.1
            - 8.8.8.8

    mysql:
        image: mysql:8.0
        container_name: tbs_mysql
        environment:
            MYSQL_DATABASE: tbs_app
            MYSQL_USER: tbs_user_app
            MYSQL_PASSWORD: tbs_secret
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3307:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - tbs_net

networks:
    tbs_net:

volumes:
    mysql_data:
